select *
from EST_FRAMEWORK.T_BEV_GROUP_STANDARD;
insert into EST_FRAMEWORK.T_BEV_GROUP_STANDARD (ID, TASK_ID, GROUP_ID, SCOPE_ID, TYPE, NAME, PRICE, PRICE_TOTAL, FWYT,
                                                FWYT3, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME)
values ();